extends "../core/ApiBee.gd"

const Build = preload("../models/Build.gd")

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# API BuildV1Api
# Instantiate this object and use it to make requests to the API.

func _bzz_get_api_name() -> String:
	return "BuildV1Api"


# Operation createBuild → POST /builds/v1/{appId}/create
func create_build(
	# appId: String = ""   Eg: appId_example
	# 
	appId: String,
	on_success: Callable = Callable(),  # func(response: ApiResponse)
	on_failure: Callable = Callable(),  # func(error: ApiError)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("POST")

	# Compute the URL path to the API resource
	var bzz_path := "/builds/v1/{appId}/create".replace("{" + "appId" + "}", _bzz_urlize_path_param(appId))

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_produced_by_server := ['application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()

	var bzz_body = null

	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, bzz_body,
		func(bzz_response):
			bzz_response.data = Build.bzz_denormalize_single(bzz_response.data)
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)


func create_build_threaded(
	# appId: String = ""   Eg: appId_example
	# 
	appId: String,
	on_success: Callable = Callable(),  # func(response: ApiResponse)
	on_failure: Callable = Callable(),  # func(error: ApiError)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "create_build")
	bzz_callable.bind(
		appId,
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread


# Operation deleteBuild → DELETE /builds/v1/{appId}/delete/{buildId}
func delete_build(
	# appId: String = ""   Eg: appId_example
	# 
	appId: String,
	# buildId: int   Eg: 1.2
	# 
	buildId: int,
	on_success: Callable = Callable(),  # func(response: ApiResponse)
	on_failure: Callable = Callable(),  # func(error: ApiError)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("DELETE")

	# Compute the URL path to the API resource
	var bzz_path := "/builds/v1/{appId}/delete/{buildId}".replace("{" + "appId" + "}", _bzz_urlize_path_param(appId)).replace("{" + "buildId" + "}", _bzz_urlize_path_param(buildId))

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_produced_by_server := ['application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()

	var bzz_body = null

	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, bzz_body,
		func(bzz_response):
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)


func delete_build_threaded(
	# appId: String = ""   Eg: appId_example
	# 
	appId: String,
	# buildId: int   Eg: 1.2
	# 
	buildId: int,
	on_success: Callable = Callable(),  # func(response: ApiResponse)
	on_failure: Callable = Callable(),  # func(error: ApiError)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "delete_build")
	bzz_callable.bind(
		appId,
		buildId,
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread


# Operation getBuildInfo → GET /builds/v1/{appId}/info/{buildId}
func get_build_info(
	# appId: String = ""   Eg: appId_example
	# 
	appId: String,
	# buildId: int   Eg: 1.2
	# 
	buildId: int,
	on_success: Callable = Callable(),  # func(response: ApiResponse)
	on_failure: Callable = Callable(),  # func(error: ApiError)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("GET")

	# Compute the URL path to the API resource
	var bzz_path := "/builds/v1/{appId}/info/{buildId}".replace("{" + "appId" + "}", _bzz_urlize_path_param(appId)).replace("{" + "buildId" + "}", _bzz_urlize_path_param(buildId))

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_produced_by_server := ['application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()

	var bzz_body = null

	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, bzz_body,
		func(bzz_response):
			bzz_response.data = Build.bzz_denormalize_single(bzz_response.data)
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)


func get_build_info_threaded(
	# appId: String = ""   Eg: appId_example
	# 
	appId: String,
	# buildId: int   Eg: 1.2
	# 
	buildId: int,
	on_success: Callable = Callable(),  # func(response: ApiResponse)
	on_failure: Callable = Callable(),  # func(error: ApiError)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "get_build_info")
	bzz_callable.bind(
		appId,
		buildId,
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread


# Operation getBuilds → GET /builds/v1/{appId}/list
func get_builds(
	# appId: String = ""   Eg: appId_example
	# 
	appId: String,
	on_success: Callable = Callable(),  # func(response: ApiResponse)
	on_failure: Callable = Callable(),  # func(error: ApiError)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("GET")

	# Compute the URL path to the API resource
	var bzz_path := "/builds/v1/{appId}/list".replace("{" + "appId" + "}", _bzz_urlize_path_param(appId))

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_produced_by_server := ['application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()

	var bzz_body = null

	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, bzz_body,
		func(bzz_response):
			bzz_response.data = Build.bzz_denormalize_multiple(bzz_response.data)
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)


func get_builds_threaded(
	# appId: String = ""   Eg: appId_example
	# 
	appId: String,
	on_success: Callable = Callable(),  # func(response: ApiResponse)
	on_failure: Callable = Callable(),  # func(error: ApiError)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "get_builds")
	bzz_callable.bind(
		appId,
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread


# Operation runBuild → POST /builds/v1/{appId}/run/{buildId}
func run_build(
	# appId: String = ""   Eg: appId_example
	# 
	appId: String,
	# buildId: int   Eg: 1.2
	# 
	buildId: int,
	# file: PackedByteArray   Eg: BINARY_DATA_HERE
	# 
	file: PackedByteArray,
	on_success: Callable = Callable(),  # func(response: ApiResponse)
	on_failure: Callable = Callable(),  # func(error: ApiError)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("POST")

	# Compute the URL path to the API resource
	var bzz_path := "/builds/v1/{appId}/run/{buildId}".replace("{" + "appId" + "}", _bzz_urlize_path_param(appId)).replace("{" + "buildId" + "}", _bzz_urlize_path_param(buildId))

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_consumable_by_server := ['multipart/form-data']
	var bzz_found_producible_mime := false
	for bzz_mime in BZZ_PRODUCIBLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_consumable_by_server:
			bzz_headers["Content-Type"] = bzz_mime
			bzz_found_producible_mime = true
			break
	if not bzz_found_producible_mime:
		var error := ApiError.new()
		error.identifier = "run_build.headers.content_type"
		error.message = "That endpoint only accepts %s as content type(s) and none are supported by this client."
		on_failure.call(error)
		return
	var bzz_mimes_produced_by_server := ['text/plain', 'application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()

	# ADDED MANUALLY [HATHORA]
	var file_content = PackedByteArray()
	file_content.append_array("\r\n--WebKitFormBoundaryePkpFF7tjBAqy44L\r\n".to_utf8_buffer())
	file_content.append_array("Content-Disposition: form-data; name=\"file\"; filename=\"file.tgz\"\r\n".to_utf8_buffer())
	file_content.append_array("Content-Type: application/octet-stream\r\n\r\n".to_utf8_buffer())
	file_content.append_array(file)
	file_content.append_array("\r\n--WebKitFormBoundaryePkpFF7tjBAqy44L--\r\n".to_utf8_buffer())

	bzz_headers["Content-Type"] = "multipart/form-data; boundary=WebKitFormBoundaryePkpFF7tjBAqy44L"

	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, file_content,
		func(bzz_response):
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)

# TODO: needs to be updated like above if going to use
func run_build_threaded(
	# appId: String = ""   Eg: appId_example
	# 
	appId: String,
	# buildId: int   Eg: 1.2
	# 
	buildId: int,
	# file: String   Eg: BINARY_DATA_HERE
	# 
	file: String,
	on_success: Callable = Callable(),  # func(response: ApiResponse)
	on_failure: Callable = Callable(),  # func(error: ApiError)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "run_build")
	bzz_callable.bind(
		appId,
		buildId,
		file,
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread


