extends "../core/ApiBee.gd"

const CreateRoomRequest = preload("../models/CreateRoomRequest.gd")
const DeploymentConfig = preload("../models/DeploymentConfig.gd")
const Deployment = preload("../models/Deployment.gd")

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# API DeploymentV1Api
# Instantiate this object and use it to make requests to the API.

func _bzz_get_api_name() -> String:
	return "DeploymentV1Api"


# Operation createDeployment → POST /deployments/v1/{appId}/create/{buildId}
func create_deployment(
	# appId: String = ""   Eg: appId_example
	# 
	appId: String,
	# buildId: int   Eg: 1.2
	# 
	buildId: int,
	# deploymentConfig: DeploymentConfig
	# 
	deploymentConfig: DeploymentConfig,
	on_success: Callable = Callable(),  # func(response: ApiResponse)
	on_failure: Callable = Callable(),  # func(error: ApiError)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("POST")

	# Compute the URL path to the API resource
	var bzz_path := "/deployments/v1/{appId}/create/{buildId}".replace("{" + "appId" + "}", _bzz_urlize_path_param(appId)).replace("{" + "buildId" + "}", _bzz_urlize_path_param(buildId))

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_consumable_by_server := ['application/json']
	var bzz_found_producible_mime := false
	for bzz_mime in BZZ_PRODUCIBLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_consumable_by_server:
			bzz_headers["Content-Type"] = bzz_mime
			bzz_found_producible_mime = true
			break
	if not bzz_found_producible_mime:
		var error := ApiError.new()
		error.identifier = "create_deployment.headers.content_type"
		error.message = "That endpoint only accepts %s as content type(s) and none are supported by this client."
		on_failure.call(error)
		return
	var bzz_mimes_produced_by_server := ['application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()

	var bzz_body = null
	bzz_body = deploymentConfig
	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, bzz_body,
		func(bzz_response):
			bzz_response.data = Deployment.bzz_denormalize_single(bzz_response.data)
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)


func create_deployment_threaded(
	# appId: String = ""   Eg: appId_example
	# 
	appId: String,
	# buildId: int   Eg: 1.2
	# 
	buildId: int,
	# deploymentConfig: DeploymentConfig
	# 
	deploymentConfig: DeploymentConfig,
	on_success: Callable = Callable(),  # func(response: ApiResponse)
	on_failure: Callable = Callable(),  # func(error: ApiError)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "create_deployment")
	bzz_callable.bind(
		appId,
		buildId,
		deploymentConfig,
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread


# Operation getDeploymentInfo → GET /deployments/v1/{appId}/info/{deploymentId}
func get_deployment_info(
	# appId: String = ""   Eg: appId_example
	# 
	appId: String,
	# deploymentId: int   Eg: 1.2
	# 
	deploymentId: int,
	on_success: Callable = Callable(),  # func(response: ApiResponse)
	on_failure: Callable = Callable(),  # func(error: ApiError)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("GET")

	# Compute the URL path to the API resource
	var bzz_path := "/deployments/v1/{appId}/info/{deploymentId}".replace("{" + "appId" + "}", _bzz_urlize_path_param(appId)).replace("{" + "deploymentId" + "}", _bzz_urlize_path_param(deploymentId))

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_produced_by_server := ['application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()

	var bzz_body = null

	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, bzz_body,
		func(bzz_response):
			bzz_response.data = Deployment.bzz_denormalize_single(bzz_response.data)
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)


func get_deployment_info_threaded(
	# appId: String = ""   Eg: appId_example
	# 
	appId: String,
	# deploymentId: int   Eg: 1.2
	# 
	deploymentId: int,
	on_success: Callable = Callable(),  # func(response: ApiResponse)
	on_failure: Callable = Callable(),  # func(error: ApiError)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "get_deployment_info")
	bzz_callable.bind(
		appId,
		deploymentId,
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread


# Operation getDeployments → GET /deployments/v1/{appId}/list
func get_deployments(
	# appId: String = ""   Eg: appId_example
	# 
	appId: String,
	on_success: Callable = Callable(),  # func(response: ApiResponse)
	on_failure: Callable = Callable(),  # func(error: ApiError)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("GET")

	# Compute the URL path to the API resource
	var bzz_path := "/deployments/v1/{appId}/list".replace("{" + "appId" + "}", _bzz_urlize_path_param(appId))

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_produced_by_server := ['application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()

	var bzz_body = null

	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, bzz_body,
		func(bzz_response):
			bzz_response.data = Deployment.bzz_denormalize_multiple(bzz_response.data)
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)


func get_deployments_threaded(
	# appId: String = ""   Eg: appId_example
	# 
	appId: String,
	on_success: Callable = Callable(),  # func(response: ApiResponse)
	on_failure: Callable = Callable(),  # func(error: ApiError)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "get_deployments")
	bzz_callable.bind(
		appId,
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread


